// TODO: Update data
export const siteConfig = {
  name: 'Create Next App',
  url: 'site.com',
  ogImage: 'https://site.com/og.jpg',
  description: 'Generated by create next app',
  links: {
    twitter: 'https://twitter.com/',
    github: 'https://github.com/',
  },
  navItems: [
    {
      href: '',
      label: '',
    },
  ],
}

export const META_THEME_COLORS = {
  light: '#ffffff',
  dark: '#09090b',
}
